bucket-back/bucket-back-backend

src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/domains/member/application/dto/request/SignupMemberServiceRequest.java, src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
<br>
OMCT-38
회원가입 기능을 개발했습니다.
멤버 엔티티에 validation 로직은 백엔드 validation 회의 이후에 추가하겠습니다!
로직이 단순해서 코드 컨벤션 위주로 봐주시면 좋을 것 같습니당 😇
<br>
=> [OMCT-38] Member 회원가입 기능 구현

build.gradle, src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/CoupangCrawler.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/DanawaCrawler.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/ItemInfo.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/NaverCrawler.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/WebCrawler.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/WebSite.java, src/main/java/com/programmers/bucketback/domains/item/domain/Item.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-48
네이버쇼핑, 다나와, 쿠팡 사이트의 상품 상세 정보를 입력하면,
각각의 상품명, 상품이미지링크, 가격정보, 원본url정보를 크롤링할 수 있다.
=> service에 작동 방법에 대한 로직을 작성해놔서 그부분을 참고해서 api를 개발하면 될것 같습니다
질문 : crawling을 application패키지에 넣었는데 (이곳에서만 사용할 것 같음) 괜찮은지?
<br>
=> [OMCT-48] : Item 크롤링 기능 구현

build.gradle, src/main/java/com/programmers/bucketback/global/config/SwaggerConfiguration.java
<br>
OMCT-52
스웨거 버전 업데이트로 결과를 확인함
<br>
swagger가 springboot3에 맞도록 버전을 업데이트함
=> [OMCT-52] Swagger 버전 업데이트

src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/domains/member/application/dto/response/LoginMemberServiceResponse.java
<br>
NO-ZIRA
- 기존에는 로그인 시 닉네임과 jwt 토큰만 반환하였는데, API 수정에 맞게 회원 아이디도 반환하도록 추가하였습니다.
<br>
=> [NO-ZIRA] 로그인 시 memberId 반환

src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java, src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
<br>
OMCT-66
- 회원 삭제 기능 구현했습니다!
<br>
=> [OMCT-66] Member 삭제 기능 구현

src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/domains/member/application/dto/request/UpdateProfileMemberServiceRequest.java, src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java, src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
<br>
OMCT-65
- 프로필 수정 기능을 구현하였습니다.
<br>
=> [OMCT-65] Member 프로필 수정 기능 구현

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/bucket/api/BucketUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketRemover.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java, src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
53 
버킷 수정 및 삭제 기능을 구현함
53에서 파생된 브랜치로 56 merge후 -> 53 merge해서 main에 반영할 예정
<br>
=> [OMCT - 56] Bucket 수정 및 삭제 기능 구현

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/bucket/api/BucketCreateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketContent.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java, src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java, src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java, src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketItem.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java, src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
53 : bucket생성 기능 구현
개념객체, embedded를 활용해서 구현해보았습니다~
유저 id정보가 들어가야하는 부분, 다른 곳에서 예외처리해야 하는부분은 임시로 빼두었어요
<br>
=> [OMCT - 53 ] Bucket 생성 구현

src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteCreateResponse.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/CreateVoteServiceRequest.java, src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java, src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
<br>
OMCT-71
투표 생성 기능을 구현하였습니다.
추가로 Voter 클래스도 미리 만들어두었습니다.
<br>
=> [OMCT-71] Vote 생성 기능 구현

build.gradle, src/main/java/com/programmers/bucketback/global/config/QuerydslConfig.java
<br>
NO-JIRA
query dsl 관련 의존성 추가와 qclass가 build폴더 하위에 생성되게 만들었습니다!
=> build: query dsl 설정파일 추가

src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
<br>
NO-JIRA
- Vote와 Item 사이의 연관 관계 제거
- Vote에서 itemId를 필드로 갖고 있도록 변경
<br>
=> [NO-JIRA] Item과 Vote 연관관계 제거

src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewReader.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewContent.java, src/main/java/com/programmers/bucketback/domains/review/domain/Review.java, src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
[OMCT-43]
리뷰 등록 기능 추가 
[OMCT-43]: https://ohmycourse.atlassian.net/browse/OMCT-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-43] 리뷰 등록 기능 추가

src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java, src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
<br>
NO-JIRA
review 엔티티에서 item 클래스가 아니라 item id만 가지도록 변경
이번 PR에서 변경하는 로직을 제외하고 review엔티티에 있는 item클래스를 사용하는 곳은 없어서 기존에 있던 기능에 영향을 주지 않습니다.
=> [NO-JIRA] review 엔티티에서 item id를 가지도록 변경

src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteRemover.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-93
- 투표 삭제 기능 구현
- 투표 작성자만 삭제할 수 있음
- 투표 삭제되면 해당 투표의 투표자도 모두 삭제
<br>
=> [OMCT-93] Vote 삭제 기능 구현

src/main/java/com/programmers/bucketback/domains/common/MemberUtils.java, src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
<br>
NO-JIRA
- ROLE 확인을 통해 회원, 비회원 구분하는 로직을 추가하였습니다.
- `MemberUtils.gerCurrentId` 메서드 전에 무조건 `MemberUtils.isLoggedIn` 메서드로 로그인 여부 확인 필수
<br>
=> [NO-JIRA] 회원 비회원 구분 로직 추가

src/main/java/com/programmers/bucketback/global/config/SwaggerConfiguration.java
<br>
N/A
swagger에 인증 토큰을 넣어서 테스트할 수 있는 기능을 제공할 수 있습니다.
<br>
=> [NO-JIRA] swagger authentication 설정 로직 추가

src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewModifier.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewReader.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewValidator.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
=> [OMCT-44] Review 수정 기능 추가

src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewRemover.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewValidator.java
=> [OMCT-97] review 삭제 기능 구현

build.gradle
<br>
N/A
- Mysql Connector 추가
<br>
=> [NO-JIRA] MySQL 관련 의존성 추가

src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, src/main/java/com/programmers/bucketback/domains/item/application/MemberItemChecker.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemServiceResponse.java, src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewStatistics.java, src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
<br>
OMCT-37
- 아이템 상세조회 기능 구현
- 평균 평점은 2번째 자리에서 반올림 하도록 구현
- 만약 로그인한 사용자가 아이템 담기한 아이템이면 itemIsMine이 true로 반환
<br>
=> [OMCT-37] 아이템 상세 조회 기능 구현 

src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java, src/main/java/com/programmers/bucketback/domains/vote/application/OptionItem.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteCounter.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteInfo.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoterReader.java, src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVoteServiceResponse.java, src/main/java/com/programmers/bucketback/domains/vote/repository/VoterRepository.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-94
- 현재 application 패키지 내에 OptionItem 클래스를 만들어서 DTO로 사용하고 있는데, 추후 병곤님이 ItemInfo를 만드시면 그걸로 변경하려고 합니다.
- 회원일 때만 선택 아이템 ID를 반환하도록 구현하였습니다.
- 서비스 코드는 어디까지 비지니스 로직인지 내일 더 고민해보고 리팩토링 할 예정입니다!
<br>
=> [OMCT-94] 투표 상세 조회 기능 구현

src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetNamesResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemFinder.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemNameResult.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemNamesServiceResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemNameGetResult.java, src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepository.java
<br>
[OMCT-99]
키워드를 입력하면 아이템 이름가져오는 기능 구현 
- 빈칸 입력시 빈 리스트를 반환 합니다. (예외발생 X)
- 좌우 공백은 trim으로 날리고 검색합니다. 
[OMCT-99]: https://ohmycourse.atlassian.net/browse/OMCT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-99] 키워드로 아이템 이름 가져오기 기능 구현

.github/workflows/CICD.yml
<br>
N/A
- Gihub Secret에 application.yml 내용(Mail 설정 관련)을 base64 인코드하여 저장
- 저장된 Secret를 사용하여 application.yml 생성
<br>
=> [NO-JIRA] CICD.yml에 mail properties 설정 추가

build.gradle, src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberCheckEmailResponse.java, src/main/java/com/programmers/bucketback/domains/member/application/EmailSender.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberChecker.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/domains/member/repository/MemberRepository.java, src/main/java/com/programmers/bucketback/global/config/MailConfiguration.java, src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-73
- 이메일 중복 확인 -> 중복 이메일이라면 예외 발생
- 이메일 중복이 아니라면 해당 이메일로 회원가입 인증번호 발송
<br>
=> [OMCT-73] 이메일 중복 확인 + 인증번호 전송 기능 구현

src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemMapper.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/GetItemServiceResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/vo/ItemInfo.java
<br>
NO-JIRA
ItemInfo 클래스 생성 및 response 수정
=> [NO-JIRA] ItemInfo 클래스 생성 및 response 수정

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java, src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketContent.java, src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketCursorSummary.java, src/main/java/com/programmers/bucketback/domains/bucket/application/vo/BucketItemContent.java, src/main/java/com/programmers/bucketback/domains/bucket/application/vo/ItemImage.java, src/main/java/com/programmers/bucketback/domains/common/vo/CursorRequest.java
<br>
123
응답값 변수명 수정, required=true 삭제, jsoninclude 적용
<br>
=> [OMCT-123] bucket api 통일, 변수명 수정

src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java
<br>
NO-JIRA 
member info 개념객체 추가 했습니다.
=> [NO-JIRA] member info 개념객체 추가

src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketItem.java, src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java, src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java, src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoriesGetResponse.java, src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetResponse.java, src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryInfoSummary.java, src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryItemGetResponse.java, src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java, src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java, src/main/java/com/programmers/bucketback/domains/inventory/domain/InventoryItem.java, src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepository.java, src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummary.java, src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummaryImpl.java, src/main/java/com/programmers/bucketback/domains/item/application/vo/ItemInfo.java
<br>
88
인벤토리의 상세 정보를 조회하고
인벤토리 목록의 요약 정보를 조회한다.
<br>
=> [OMCT-88] Inventory 조회 및 요약정보 목록 조회

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java, src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedContent.java, src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedCreateRequest.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedAppender.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedModifier.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedRemover.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, src/main/java/com/programmers/bucketback/domains/feed/domain/FeedItem.java, src/main/java/com/programmers/bucketback/global/config/SwaggerConfiguration.java
<br>
89
피드를 생성하는데, bucket로부터 정보를 가져와서 구현합니다.
<br>
=> [OMCT-89] 피드 생성 로직 구현

src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java, src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewCursorReader.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, src/main/java/com/programmers/bucketback/domains/review/application/dto/GetReviewByCursorServiceResponse.java, src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewCursorSummary.java, src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewSummary.java, src/main/java/com/programmers/bucketback/domains/review/domain/Review.java, src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java, src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursor.java, src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
<br>
[OMCT-98] 
리뷰목록 조회 커서 방식으로 구현
<br>
[OMCT-98]: https://ohmycourse.atlassian.net/browse/OMCT-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-98] 리뷰 목록 조회 커서방식으로 구현

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java, src/main/java/com/programmers/bucketback/domains/common/Hobby.java, src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java, src/main/java/com/programmers/bucketback/domains/inventory/api/dto/request/InventoryCreateRequest.java, src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryInfoSummary.java, src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryModifier.java, src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryReader.java, src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java, src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java, src/main/java/com/programmers/bucketback/domains/inventory/repository/InventoryRepositoryForSummaryImpl.java
<br>
api가 실행되지 않는 문제 해결, lazy initialization 해결
124
N/A
inventory관련 api로직을 수정한다. 
문제점 : 유저의 취미별 인벤토리, 인벤토리의 아이템 이미지 정보들이 첫번째 값만 묶여져서 나옴
<br>
=> [OMCT-124] 인벤토리 로직 전체 리팩토링

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedCreateRequest.java, src/main/java/com/programmers/bucketback/domains/feed/api/request/FeedUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedAppender.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedModifier.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedRemover.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCreateContent.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedUpdateContent.java, src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepository.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
90
피드 수정 : 본문 내용이 수정되는 로직, 일단 이름이 겹쳐서 message라고 변수명은 처리함
피드 삭제 로직 구현 
<br>
=> [OMCT-90] 피드 수정 및 삭제 로직 구현

src/main/java/com/programmers/bucketback/domains/item/application/EnrollItemService.java, src/main/java/com/programmers/bucketback/domains/item/application/EnrollItemValidator.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemAppender.java, src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepository.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-39
아이템 등록하면 아이템 담기, 로그인 확인 기능, 주소 중복 확인 기능 추가
=> [OMCT-39] 아이템 등록 기능 추가 

src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedAppender.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedRemover.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, src/main/java/com/programmers/bucketback/domains/feed/domain/FeedLike.java, src/main/java/com/programmers/bucketback/domains/feed/repository/FeedLikeRepository.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
130
피드 좋아요 및 좋아요 취소 기능을 구현함
이미 좋아요 했는데 좋아요를 시도하는 경우와,
이미 좋아요 취소가 되어있지만, 좋아요 취소를 시도하는 경우에 대한 예외 처리를 진행함 
질문 : 이 검증로직을 시도하는 경우 try-catch문을 활용하는게 좋을지 지금과 같은 방법이 좋은지 궁금합니다. 
<br>
=> [OMCT-130] 피드 좋아요 및 좋아요 취소 기능 구현

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentAppender.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java, src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java, src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepository.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java, src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-127
- 피드 댓글 생성 기능을 구현하였습니다!
<br>
=> [OMCT-127] Feed 댓글 생성

src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewRemover.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java
<br>
[OMCT-158]
리뷰 삭제 기능 추가
[OMCT-158]: https://ohmycourse.atlassian.net/browse/OMCT-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-158] 리뷰 삭제 기능 추가

src/main/java/com/programmers/bucketback/domains/hobby/HobbyController.java, src/main/java/com/programmers/bucketback/domains/hobby/api/dto/response/HobbyGetResponse.java, src/main/java/com/programmers/bucketback/domains/hobby/application/HobbyService.java
<br>
[OMCT-137] 
취미 조회 기능 추가
[OMCT-137]: https://ohmycourse.atlassian.net/browse/OMCT-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-137] 취미 조회 기능 추가

src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
<br>
NO-JIRA
나의 아이템 생성에 경로가 잘못되어 수정하였습니다!
=> [NO-JIRA] 아이템 도메인 잘못된 경로 수정

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentModifier.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentReader.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentValidator.java, src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
=> [OMCT-136] 피드 댓글 수정 기능 추가

src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteManager.java, src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, src/main/java/com/programmers/bucketback/domains/vote/repository/VoterRepository.java
<br>
OMCT-140
- 투표가 이미 취소된 경우에는 아무일도 하지 않고, 취소가 되지 않았을 경우에만 투표 취소가 되도록 구현하였습니다.
<br>
=> [OMCT-140] Vote 취소 기능 구현

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentModifier.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentReader.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java, src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java, src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-128
- 피드 작성자는 본인의 댓글을 제외하고 댓글을 채택할 수 있습니다.
질문: validator를 사용하면 read 메서드가 중복으로 발생합니다. 그래서 저는 validator를 쓰지 않고 구현하였는데 이 부분에 대해서 팀원들과 상의하고 싶습니다!
<br>
=> [OMCT-128] 댓글 채택 기능 구현

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentCursorSummary.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentGetCursorResponse.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentReader.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java, src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepository.java, src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursor.java, src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursorImpl.java, src/main/java/com/programmers/bucketback/domains/comment/repository/CommentSummary.java
<br>
129
피드 댓글 목록을 커서 방식으로 조회합니다.
<br>
=> [OMCT-129] 피드 댓글 목록 조회

src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetResponse.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/GetFeedServiceResponse.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedInfo.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedItemInfo.java, src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java
<br>
OMCT-126
- 피드 상세 조회 구현
- `isLiked`는 로그인한 사용자일 때만 표시
<br>
=> [OMCT-126] Feed 상세 조회 구현

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentRemover.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
<br>
[OMCT-135]
피드 댓글 삭제 기능 추가
[OMCT-135]: https://ohmycourse.atlassian.net/browse/OMCT-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-135] 피드 댓글 삭제 기능 추가

src/main/java/com/programmers/bucketback/domains/comment/domain/Comment.java, src/main/java/com/programmers/bucketback/domains/comment/domain/vo/Content.java, src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberAppender.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberManager.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberModifier.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberReader.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberRemover.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, src/main/java/com/programmers/bucketback/domains/member/application/MemberUpdater.java, src/main/java/com/programmers/bucketback/domains/member/application/SecurityManager.java, src/main/java/com/programmers/bucketback/domains/member/application/dto/response/LoginMemberServiceResponse.java, src/main/java/com/programmers/bucketback/domains/member/domain/LoginInfo.java, src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, src/main/java/com/programmers/bucketback/domains/member/domain/MemberStatus.java, src/main/java/com/programmers/bucketback/domains/member/domain/Nickname.java, src/main/java/com/programmers/bucketback/domains/member/domain/Role.java, src/main/java/com/programmers/bucketback/domains/member/domain/vo/Introduction.java, src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java, src/main/java/com/programmers/bucketback/domains/member/domain/vo/MemberStatus.java, src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java, src/main/java/com/programmers/bucketback/domains/member/domain/vo/Role.java, src/main/java/com/programmers/bucketback/domains/member/repository/MemberRepository.java, src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java, src/main/java/com/programmers/bucketback/domains/vote/domain/vo/Content.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
NO-JIRA
- 로그인 없이 회원 삭제, 회원 정보 수정할 경우 예외 처리 35b806d7a8b348e05ed85b61a8f972051c72c36a
- 비밀번호 수정 시 암호화 안되는 버그 해결 58a494501e0fe73e7619fc28b668e7ac00b705d2
- 프로필 수정 시 닉네임 중복 체크 8f0cfbdbf2a8eaaaaad168475eb367c6cce016fc
- 닉네임 중복일 떄 예외 발생 272a5d53ae95c1ff21a1219e414fe3faa30608fa
- 회원가입 시 이메일, 닉네임 중복 체크 f7d1fe3f92b868541f97cd0d24cfb26d3363bd6b
> 유효성 검증이 필요한 필드들은 모두 VO로 만들었습니다!
- 닉네임 유효성 검증 추가 798bf37f92af42ca0381a35ed1415a5da34ce913
- 비밀번호 유효성 검사 추가 58a494501e0fe73e7619fc28b668e7ac00b705d2
- 자기소개 유효성 검사 추가 b2e2e48c6cde0e61f0660d544e9b353caa936210
> 유효성 검증을 다 처리하다가 memer가 아닌 vote와 comment 까지도 해버렸습니다ㅎㅎ..😅
- 투표 내용 유효성 검사 추가 b9ced6e63138c5184072a63fa431e17236d2ec95
- comment 유효성 검사 추가 aa81314500fc68b96895ac27d09443f4329fb64c
- 이메일 유효성 검사
- DTO 에서 유효성 검사
<br>
=> [NO-JIRA] Member 버그 수정 및 유효성 검증 추가

src/main/java/com/programmers/bucketback/domains/comment/application/CommentAppender.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentModifier.java, src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedReader.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedInfo.java, src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, src/main/java/com/programmers/bucketback/domains/member/application/vo/MemberInfo.java
<br>
NO-JIRA
- 피드 상세 조회 구현로직과 비지니스 로직 구분
- 댓글 생성 시 회원 검증 로직 서비스로 이동
- 댓글 채택할 때 필요한 검증 로직 서비스로 이동
<br>
=> [NO-JIRA] Feed 상세 조회 & Comment 생성, 채택 리팩토링

src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java
<br>
205
+ 프론트 측에서 회원가입과 로그인 상황 인증인가 요청 문제가 있었음
+ url로 직접 입력을 하면 문제가 해결되지만 개발 서버(localhost)에서 보내는 요청에서는 요청이 막혀있는 문제가 있었음
가장 의심되는 부분 : cors 문제 
동일 서버에서 프론트와 백 개발이 이루어지지 않고 각자 다른 서버에서 테스트를 하는 경우 cors문제가 발생한다. 
CorsConfiguration 을 설정해서 문제를 해결함
추가 구현 기능 : api 인증 인가가 필요 없는 로직들은 시큐리티 필터를 타지 않도록 하고 나머지 기능은 인증인가 정보를 확인하도록 설정함
<br>
=> [OMCT-205] security cors 설정 및 인증인가 api 선별

src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java, src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteParticipateRequest.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-208
[feat: Email 유효성 검증 추가](https://github.com/bucket-back/bucket-back-backend/commit/54dc1066a94db3c1102c141892eb39479272febe)
[feat: member api dto validation 추가](https://github.com/bucket-back/bucket-back-backend/commit/14638dcbbf98f09d6f75fe3abda32007efa70162)
[feat: vote api dto validation 추가](https://github.com/bucket-back/bucket-back-backend/commit/2d06b0c45873ba186cde666213f583d20379b693)
[feat: comment api dto validation 추가](https://github.com/bucket-back/bucket-back-backend/commit/be419466d254e0859329b0e6f1a874dda4fc4df8)
<br>
=> [OMCT-208] 회원, 투표, 피드 상세 조회, 댓글 생성, 댓글 채택 API DTO 유효성 검증 추가

src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-207
- 만료된 토큰 예외는 필터에서 발생하기 때문에 HandlerExceptionResolver를 사용하여 ExceptionHandler에서 처리할 수 있도록 했습니다.
<br>
=> [OMCT-207] 만료 JWT 토큰 예외 처리

src/main/java/com/programmers/bucketback/domains/common/Hobby.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemCursorReader.java, src/main/java/com/programmers/bucketback/domains/item/application/MemberItemAppender.java, src/main/java/com/programmers/bucketback/domains/item/application/MemberItemValidator.java, src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java, src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java, src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-200
- 아이템 검색 목록 조회에서 중복으로 아이템을 반환하는 버그 수정 c0f21df8b70af867586814e0bbad6f6f0cf5d8c6
- 잘못된 hobby enum을 입력할 경우 옳바른 예외를 반환할 수 있도록 수정 95a37642e0606e9b3008bf84f1318698faa2b93f
- dto에서 잘못된 값을 입력받을 경우 반환하는 예외 메시지 설정 9f04d41ae746c857f1d49bff4bbfe027d6da7a63
- 아이템 담기를 할 때 사용자가 이미 담은 아이템이 있을 경우 예외를 반환 하도록 기능 추가 0c82f7629f9d96ac06d07bf2418f3aa1df7f8790
- 사용자가 담은 아이템이 있는지 확인하는 JPQL 메서드 추가 7587e4a1f9e8ea32bdad63d3e1c454a5c01ee9a3
- 아이템 목록조회를 가독성과 책임을 생각하여 리팩토링 5c1626f9d4675be0522dc6b92dc73c5f424cc1a6
<br>
=> [OMCT-200] 아이템 버그 수정 및 유효성 검사 추가 

src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewCursorReader.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewModifier.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetByCursorServiceResponse.java, src/main/java/com/programmers/bucketback/domains/review/application/vo/ReviewContent.java, src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
<br>
- 서비스 계층에 새롭게 적용된 클래스명 컨벤션을 적용하여 클래스명을 변경하였습니다. f4c4137321e95725d3d92d66f6c3c0b5f30b386f
- 참조관계를 고려하여 반환 받은 response를 toInstance에서 static from으로 변경 하였습니다. 78d28a8b66439dad5d145d6f40ca7563d66f3e98
- 리뷰 목록 조회 리팩토링 79838d245ae99b838ad9d062d816a12c60398314
N/A
<br>
=> [OMCT-198] 리뷰 리팩토링 

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java, src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckEmailRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java, src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java, src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteParticipateRequest.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-206
- 회원 전체
- 투표 전체
- 피드 상세조회
- 댓글 생성, 채택
- 회원 비밀번호 길이 수정 10 -> 15
<br>
=> [OMCT-206] Swagger 설명 추가

src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketCreateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/request/BucketUpdateRequest.java, src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketCreateResponse.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketAppender.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketModifier.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketReader.java, src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
166
<br>
1. 지연 초기화 문제 수정
2. 버킷에 아이템 아이디가 오지 않는 경우(null이 아니고, 빈 리스트로 오는 경우) 검증 추가
=> [OMCT-166] 버킷 리팩토링 검증로직 추가

src/main/java/com/programmers/bucketback/domains/common/Hobby.java, src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemAddResponse.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemEnrollResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemCursorReader.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java, src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, src/main/java/com/programmers/bucketback/domains/item/application/MemberItemAppender.java, src/main/java/com/programmers/bucketback/domains/item/application/MemberItemValidator.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemAddServiceResponse.java, src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemEnrollServiceResponse.java, src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java, src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java, src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
<br>
NO-JIRA
아이템 등록, 아이템 담기할 경우 아이템 아이디 반환 기능 추가
<br>
=> [NO-JIRA] 아이템 등록, 아이템 담기할 경우 아이템 아이디 반환 기능 추가

src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewCreateResponse.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewAppender.java, src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewCreateServiceResponse.java
<br>
OMCT-214
리뷰 생성할 경우 review id 반환
=> [OMCT-214] 리뷰 생성할 경우 review id 반환

src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
=> [OMCT-210] 피드 댓글 리팩토링

src/main/java/com/programmers/bucketback/domains/item/application/crawling/CoupangCrawler.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/DanawaCrawler.java, src/main/java/com/programmers/bucketback/domains/item/application/crawling/NaverCrawler.java, src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
크롤러에서 예외를 발생할 경우 의도한 예외를 던질 수 있도록 예외 전환하는 기능 추가
- 예외를 잡는 영역이 넓어서 예외를 파악하기 힘들 것 같습니다.
- 프론트와 api 연동 일정 때문에 넓게 잡았는지만 추후에 구체적인 예외를 잡을 수 있도록 이부분은 수정이 필요할 것 같습니다. 
[NO-JIRA]
=> [NO-JIRA] 크롤러에서 예외를 발생할 경우 의도한 예외를 던질 수 있도록 예외 전환하는 기능 추가

src/main/java/com/programmers/bucketback/domains/comment/api/CommentController.java, src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java, src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java, src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/request/ItemEnrollRequest.java, src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemAddRequest.java, src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java, src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
<br>
NO-JIRA
아이템, 리뷰, 댓글에 대해 swagger 설명 추가
=> [NO-JIRA] 아이템, 리뷰, 댓글에 대해 swagger 설명 추가

src/main/java/com/programmers/bucketback/domains/hobby/HobbyController.java, src/main/java/com/programmers/bucketback/domains/hobby/api/dto/response/HobbyGetResponse.java, src/main/java/com/programmers/bucketback/domains/hobby/api/dto/response/HobbyItem.java, src/main/java/com/programmers/bucketback/domains/hobby/application/HobbyService.java
<br>
- swagger 추가 하였습니다!
- hobby api 반환 목록을 수정하여 아래와 같이 나오게 하였습니다.
```
{
"hobbies": [
{
"name": "basketball",
"value": "농구"
},
{
"name": "baseball",
"value": "야구"
},
{
"name": "soccer",
"value": "축구"
},
{
"name": "cycle",
"value": "사이클"
},
{
"name": "keyboard",
"value": "키보드"
},
{
"name": "swimming",
"value": "수영"
}
]
}
```
N/A
<br>
=> [NO-JIRA] hobby api 반환 목록 수정

src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, src/main/java/com/programmers/bucketback/domains/feed/application/FeedSortCondition.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorSummary.java, src/main/java/com/programmers/bucketback/domains/feed/application/vo/FeedCursorSummaryLike.java, src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
<br>
- 피드 목록조회에 대한swagger 추가
- content로 변수명 변경
OMCT-225
<br>
=> [OMCT-225] 피드 목록 조회 리팩토링

src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberCheckNicknameRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberLoginRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberSignupRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdatePasswordRequest.java, src/main/java/com/programmers/bucketback/domains/member/api/dto/request/MemberUpdateProfileRequest.java
<br>
N/A
- api dto에서 닉네임 max size 5 -> 25로 변경
- api dto에서 비밀번호 swagger example 16글자여서 12글자로 변경
<br>
=> [NO-JIRA] 닉네임 validation max size 변경, 비밀번호 swagger example 수정

api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java, api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewValidator.java, api/src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetByCursorServiceResponse.java, domain/src/main/java/com/programmers/bucketback/domains/review/domain/Review.java, domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReader.java, domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewStatistics.java, domain/src/main/java/com/programmers/bucketback/domains/review/model/ReviewCursorSummary.java
<br>
OMCT-240
- 멀티 모듈 적용을 위한 의존성 정리를 하였습니다.
- 리뷰 목록 조회 할 때 커서 리팩토링도 진행하였습니다.
<br>
=> [OMCT-240] 멀티모듈을 위한 리뷰 리팩토링(with 커서 리팩토링) 

api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java, api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, api/src/main/java/com/programmers/bucketback/global/config/security/SecurityManager.java, domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java, domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java, domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberAppender.java, domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberChecker.java, domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java, infrastructure/src/main/java/com/programmers/bucketback/mail/EmailSender.java
<br>
OMCT-244
- member 도메인에서 `@NotNull` 제거, `@Column(nullable=false)` 추가 ce871abf5d1cfc8d6a0bd3d35092265705c382d2
- 구현 계층에서 passwordEncoder 의존성 제거 c973f45259bf17ff960f5dcd20d505dc825a5912
- EmailSender 에서 try-catch로 예외 잡기 - d890b25e5785ad9db2bb1a541b0e2b2eba223497
<br>
=> [OMCT-244] 멀티모듈을 위한 회원 리팩토링

api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, api/src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/FeedGetServiceResponse.java, domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedReader.java, domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedDetail.java
<br>
OMCT-248
- FeedService 와 FeedReader DTO 추가 6c6f800df3d2a3e178e08244f8403b54eca5d116
- 피드 상세 조회 메서드명 변경 in FeedReader 9a752dd2bf96ecd2fcede43102dc508df290bcb4
<br>
=> [OMCT-248] 멀티모듈을 위한 피드 상세조회 리팩토링

.github/workflows/CICD.yml
<br>
멀티 모듈 적용으로 인한 yml 파일 추가 및 수정
[NO-JIRA]
<br>
=> [NO-JIRA] yml 파일 수정 

bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java, bucketback-infrastructure/build.gradle, bucketback-infrastructure/src/main/java/com/programmers/bucketback/s3/S3Manager.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/s3/config/S3Configuration.java
<br>
OMCT-252
- 팀원들과 페어 프로그래밍을 통해 회원 프로필 이미지 수정 기능 구현
- S3에는 프로필 이미지 삭제 후 새로운 프로필 이미지 등록
- 프로필 이미지 이름은 회원 Id 값을 사용하여 생성
<br>
=> [OMCT-252] S3 회원 프로필 이미지 수정 기능 구현

bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberCheckJwtResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/dto/response/MemberCheckJwtServiceResponse.java
<br>
OMCT-249
- JWT 토큰 유효성 체크를 하는 API 입니다.
- 토큰이 유효하지 않다면 예외를 발생시키고, 토큰이 유효할 경우 회원 아이디와 닉네임을 반환합니다.
- 일단 meberController에 구현을 하였습니다! 주소는 `/api/members/check/jwt` 입니다.
<br>
=> [OMCT-249] JWT 토큰 유효성 체크 API 구현

bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemCursorReader.java
<br>
NO-JIRA
아이템 검색 목록 조회에 size를 주지 않으면 예외 발생하는 버그 수정
=> [NO-JIRA] 아이템 검색 목록 조회에 size를 주지 않으면 예외 발생하는 버그 수정

bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java
<br>
NO-JIRA
아이템 등록 기능 버그 수정
- 아이템 등록할 경우 url을 넣지 않아서 발생하는 버그 수정
=> [NO-JIRA] 아이템 등록 기능 버그 수정 

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
=> [NO-JIRA] 피드 목록 조회 매직 넘버 제거 

bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
<br>
NO-JIRA
연산자를 활용하면서 괄호를 사용하지 않음
<br>
=> [NO-JIRA] 버킷 등록을 위한 버그 수정 및 매직넘버 제거

bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewAppender.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReader.java
<br>
- 필요없는 transactional 삭제
- 변수명 수정 
NO-JIRA 
<br>
=> [NO-JIRA] 리뷰 리팩토링

bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/domain/Item.java
<br>
기존 URL의 최대 길이 255에 한계가 있어 1000글자로 변경하였습니다. 
NO-JIRA
<br>
=> [NO-JIRA] 아이템 URL 길이 설정 

bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java, bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java, bucketback-api/src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java, bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java
<br>
N/A
- 잘못된 값의 JWT 토큰이 들어온 경우 SignatureException이 터집니다. 해당 예외는 필터에서 터지기 때문에 GlobalExceptionHandler가 잡을 수 없습니다. 따라서 ExpiredJwtException 처리 방법과 똑같이 HandlerExceptionResolver로 예외를 스프링 단에 보내서 처리하도록 했습니다. 
- 비지니스 예외가 아닌 예외는 RuntimeException으로 변경하였습니다.
<br>
=> [NO-JIRA] JWT 관련 예외 처리 추가 & Sercurity 관련 예외 처리 변경

bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/Bucket.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/domain/Inventory.java
- []  🐛 버그 수정
<br>
NO-JIRA
리스트 필드에 final이 붙는 문제, 디미터 법칙 해결을 위한 get메서드 사용으로 문제를 해결함
=> [NO-JIRA] list에만 final컨벤션이 붙는 문제 및 FeedContent 디미터 법칙 해결

bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java
<br>
no-jira
CursorSummary 타입에서 List 타입으로 변경
<br>
=> [NO-JIRA] 피드 댓글 목록 조회 반환 타입 수정

bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetByCursorResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetByCursorServiceResponse.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/implementation/ReviewStatistics.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/model/ReviewCursorSummary.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursor.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
<br>
- 하나의 아이템에 존재하는 총 리뷰개수와 커서 방식으로 요청한 아이템들의 크기를 구별하여 반환
- 리뷰 목록 조회 isReviewed 추가
OMCT-284
<br>
- 하나의 아이템에 존재하는 총 리뷰개수와 커서 방식으로 요청한 아이템들의 크기를 구별하여 반환
- 로그인한 사용자가 아이템을 리뷰 했는지 확인하는 isReviewed 값 추가
=> [OMCT-284] 리뷰 목록 조회 isReviewed 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/dto/response/InventoryGetResponse.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryInfoSummary.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
<br>
NO-JIRA
기존에 새로운 내용이 도입전 개발해둔 내용을 주석 해제함
hobbyValue추가로 인한 한글 값으로 데이터 반환함
<br>
=> [NO-JIRA] hobbyValue 적용, profile image,inventoryinfo 주석 해제

bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
<br>
NO-JIRA
- introduction이 introduction으로 감싸진 채로 응답되는 형식 수정 7e8bdfd4979eea5791b871f0f27330cb0965a42e
- 레벨 대신 레벨포인트가 보이는 버그 수정 e23e460828596d53bcaf814b0ead909b18f1ad95 c0c2e039f168bfe0618fa22db9250af5826ee24a
- 회원 프로필 수정 시 닉네임 변경을 하지 않을 경우 닉네임 중복 예외 발생하는 버그 수정 ee27df8c5057b1e0b3f52bce098f306c6e3a2af9
<br>
=> [NO-JIRA] 회원 관련 버그 수정

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
<br>
피드 목록조회, 리뷰 목록조회에 프로필 이미지 반환 추가
NO-JIRA
피드 목록조회, 리뷰 목록조회에 프로필 이미지 반환 추가
=> [NO-JIRA] 피드 목록조회, 리뷰 목록조회에 프로필 이미지 반환 추가

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedSortCondition.java
<br>
피드 목록 조회에서 대소문자 구분 하지 않고 정렬조건 입력 받을 수 있도록 기능 추가
[NO-JIRA]
=> [NO-JIRA] 피드 목록 조회에서 대소문자 구분 하지 않고 정렬조건 입력 받을 수 있도록 기능 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewModifyResponse.java
<br>
리뷰 수정할 때 아이템 아이디 반환 하다록 기능 추가
NO-JIRA
리뷰 수정할 때 아이템 아이디 반환 하다록 기능 추가
=> [NO-JIRA] 리뷰 수정할 때 아이템 아이디 반환 하도록 기능 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewGetResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/dto/ReviewGetServiceResponse.java
<br>
리뷰 수정을 위한 리뷰 조회 기능 추가
OMCT-294
리뷰 수정을 위한 리뷰 조회 기능 추가
=> [OMCT-294] 리뷰 수정을 위한 리뷰 조회 기능 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/application/ReviewService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, bucketback-api/src/main/java/com/programmers/bucketback/global/util/MemberUtils.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
<br>
N/A
- getCurrentMemberId로 현재 로그인한 회원의 id를 받아올 때 탈퇴 회원인지 검증하는 로직을 추가
- getCurrentMember 메서드도 추가 (현재 로그인한 회원을 반환하는 메서드)
<br>
=> [NO-JIRA] 로그인한 회원 조회 시 탈퇴 회원인지 검증하는 로직 추가

bucketback-api/build.gradle, bucketback-domain/build.gradle
<br>
no-jira
text-fixture 환경을 설정한다.
<br>
=> [NO-JIRA] test-fixture 환경 설정

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/Feed.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/domain/FeedItem.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedInfo.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
<br>
NO-JIRA
- 레벨이 잘못 나오는 버그 수정 3ef784c75c0780aaf913acb79fb43100720bae4a
- 아이템 총 가격도 응답에 추가 5bd5c8d1de4f6e9c130e7f73be351becb734f7d8
<br>
=> [NO-JIRA] 피드 상세 조회 시 레벨 잘못 나오는 버그 수정 & 아이템 총 가격 응답값 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/model/InventoryProfile.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberReader.java
<br>
1. 탈퇴한 회원의 마이페이지를 접근할 수 없도록 방어
2. 디미터 법칙으로 null인 자기소개를 조회할 때 npe가 발생하는 문제 수정
3. 인벤토리의 취미 응답값을 한글로 반환하도록 수정
no-jira
<br>
=> [NO-JIRA] 마이페이지 관련 리팩토링

bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/LoginInfo.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
<br>
NO-JIRA
- 회원 삭제할 때 이메일에 "delete" 를 뒤에 덧붙여 유효하지 않은 이메일로 변경 fa96aa34e8f248d633f1d39b74d05c3de93651ef
- 프로필 이미지 삭제 시 불필요한 회원 조회 삭제 a38e68c19b32bd0ece91df3bfb722d179400257b
<br>
=> [NO-JIRA] 회원 삭제 시 유효하지 않은 이메일로 변경 & 불필요한 로직 제거

bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketProfile.java
<br>
no-jira
마이페이지 조회시 버킷 취미값 한글로 반환
<br>
=> [no-jira] 버킷 - 취미 응답값 한글로 변경

bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursor.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
<br>
피드 목록 조회 옵션 추가
OMCT-322
- onlyLikeFeed 옵션 추가 
- onlyLikeFeed을 true로 입력받을 경우 nickname 옵션으로 입력 받은 사용자가 좋아요 누른 피드를 반환
- 만약 onlyLikeFeed가 true이고nickname이 null 경우 예외 발생
<br>
=> [OMCT-322] 피드 목록 조회 옵션 추가

bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteRemoverTest.java
<br>
OMCT-327
- 테스트 해야하는 remove 메서드는 voteRepository.delete 메서드 말고 별 다른 로직이 없기 때문에
- voteRepository.delete 메서드가 한 번 호출되었는지 확인하는 것으로 삭제 테스트를 작성했습니다.
<br>
=> [OMCT-327] VoteRemover 단위 테스트 추가

bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteManager.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoterReader.java, bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteManagerTest.java, bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoterReaderTest.java, bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/domain/VoterBuilder.java
<br>
OMCT-328
- 선택 아이템 Id를 반환하는 메서드를 먼저 리팩토링을 진행하였습니다.  aef684a2b55834297239e7a6eb21495b028e63cc
- 메서드의 분기 포인트에 따라서 각각 테스트코드를 작성하였습니다.
> 위의 3개 커밋은 이전 Pr 중복 내용이라 밑에 2개의 커밋만 확인해주시면 감사하겠습니다!!!
<br>
=> [OMCT-328] VoterReader 단위 테스트 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetResponse.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketGetServiceResponse.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/model/BucketSummary.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepositoryForCursorImpl.java
<br>
no-jira
버킷을 조회할때 아이템의 총 합계도 추가한다.
<br>
=> [No-jira] 버킷 조회(상세,목록)시 아이템의 총 금액 필드 추가

bucketback-domain/src/test/java/com/programmers/bucketback/domains/review/implementation/ReviewCursorReaderTest.java, bucketback-domain/src/testFixtures/java/com/programmers/bucketback/common/cursor/CursorPageParametersBuilder.java, bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/review/ReviewCursorSummaryBuilder.java
<br>
OMCT-344
- CursorPageParameters 필드 값이 null이 아닐 때 나의 아이템 목록 조회 테스트
- CursorPageParameters 필드 값이 null 일 때 필드를 기본 값으로 변경하여 나의 아이템 목록 조회 테스트
=> [OMCT-344] 리뷰 목록 조회 테스트

bucketback-domain/src/test/java/com/programmers/bucketback/domains/comment/implementation/CommentModifierTest.java, bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/comment/domain/CommentBuilder.java, bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/feed/FeedBuilder.java
<br>
OMCT-346
**댓글 수정 테스트**
- 댓글이 새로운 내용으로 바뀌는지를 테스트 하였습니다.
**댓글 채택 테스트**
- 댓글이 채택되면 adoption 값이 true로 바뀌는지를 테스트 하였습니다.
<br>
=> [OMCT-346]  CommentModifier 단위 테스트 추가

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
<br>
[NO-JIRA]
피드 목록 조회 limit 버그 수정
=> [NO-JIRA] 피드 목록 조회 limit 버그 수정

bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/vo/Nickname.java
<br>
NO-JIRA
- 회원이 탈퇴할 경우 이메일은 유효하지 않은 이메일로 바뀌지만 닉네임은 아무 처리가 안되고 있어서 -> 탈퇴한 회원의 닉네임을 다른 회원이 사용하지 못하는 버그가 있었습니다.
- 회원이 탈퇴할 경우 닉네임도 유효하지 않은 닉네임으로 " "로 변경함으로써 탈퇴 회원의 닉네임을 사용할 수 있게 수정하였습니다!
<br>
=> [NO-JIRA] 탈퇴한 회원 닉네임 삭제

bucketback-infrastructure/build.gradle, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/config/RedisConfig.java
<br>
NO-JIRA
- 레디스는 S3와 같은 외부 기술이라고 생각하여 인프라 모듈에 두었습니다.
- 레디스 의존성과 configuration 파일을 추가하였습니다!
<br>
=> [NO-JIRA] 레디스 설정 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetRankingResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, bucketback-infrastructure/build.gradle, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/config/RedisConfig.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/dto/ItemRankingServiceResponse.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/implement/ItemRanking.java
<br>
274
아이템 랭킹 기능을 redisTemplate을 이용해서 구현했습니다.  redis를 선택한 이유는 차후 문서화 내용참고(로컬,글로벌 캐시의 차이)
유저가 아이템을 담을 때마다 포인트가 1씩 올라가도록 구현. 그래서 top10의 랭킹을 구현함.
여기서 발생하는 랭킹을 조회하는 주기와 동시성에 대해서는 차후 디벨롭 과정에서 보완해볼 예정!
<br>
=> [OMCT-274] 아이템 랭킹 기능 구현

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
=> [NO-JIRA] 최신순으로 정렬 해서 피드를 가져올 때 최신으로 반환이 안되는 버그 수정

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
<br>
NO-JIRA
내가 좋아요 누른 피드 않보이는 버그 수정
=> [NO-JIRA] 내가 좋아요 누른 피드 않보이는 버그 수정

bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursorImpl.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
<br>
N/A
- 피드 목록 조회, 댓글 목록 조회 시 프로필 이미지 안불러와지는 버그 수정
<br>
=> [NO-JIRA] 프로필 이미지 안불러와지는 버그 수정

bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/implement/ItemRanking.java
<br>
275
아이템을 등록하는 경우, 포인트가 상승하는 경우로 나누어서 수정, 
최초 아이템을 크롤링해서 저장한 경우에도 바로 랭킹에 등록되어야 하므로 해당 케이스를 고려한 내용도 추가함
<br>
=> [OMCT-274] 아이템 랭킹 수정

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
<br>
[NO-JIRA]
좋아요 눌렀을 때 좋아요 누른 사람의 정보가 feed 작성자 처럼 반환 되는 버그 수정
=> [NO-JIRA] 좋아요 눌렀을 때 좋아요 누른 사람의 정보가 feed 작성자 처럼 반환 되는 버그 수정

bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/model/FeedItemInfo.java
<br>
[NO-JIRA]
피드 아이템에서 아이템 아이디가 아니라 피드 아이템이 반환 되는 버그 수정
=> [NO-JIRA] 피드 아이템에서 아이템 아이디가 아니라 피드 아이템이 반환 되는 버그 수정

bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentCreateRequest.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/request/CommentModifyRequest.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java, bucketback-api/src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java, bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/review/domain/Review.java
<br>
[NO-JIRA]
QA과정 중에 발견한 검증 하지 않는 영역 추가
=> [NO-JIRA] validation과 global handler exception 추가 

bucketback-infrastructure/src/main/java/com/programmers/bucketback/crawling/NaverCrawler.java
<br>
384
네이버에서 사용하는 쇼핑에서 크롤링 안되는 문제 해결
<br>
=> [OMCT-384] 네이버 쇼핑 크롤링 보완

bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/ItemGetByCursorResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemEnrollService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/dto/ItemGetByCursorServiceResponse.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemCursorReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemRemover.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepository.java
=> [NO-JIRA] 아이템 검색에 결과 전체 개수 반환 기능 추가

bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
<br>
no-jira
무한 스크롤에서 pageSize가 limit절에 걸리지 않음,
where절에서 커서 아이디 검사, limit절 추가
기존에 반영했던 내용이 수정하면서 삭제된 것으로 예상됨
<br>
=> [NO-JIRA] 인벤토리 limit쿼리 버그 해결

bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByKeywordResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteGetByKeywordServiceResponse.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java, bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
<br>
NO-JIRA
- 키워드가 들어간 아이템을 선택 옵션으로 가지고 있는 투표들을 검색하는 기능입니다.
- 키워드 검색으로 조회된 투표들의 전체 개수를 응답 반환값에 추가하였습니다.
<br>
=> [NO-JIRA] 투표 키워드 검색해서 나온 전체 결과수 반환값 추가

bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByKeywordResponse.java
<br>
NO-JIRA
- 키워드로 투표 검색을 할 때 반환되는 전체 결과 수의 필드명 변경 `totalCommentCount` -> `totalVoteCount`
<br>
=> [NO-JIRA] 잘못된 네이밍 수정

bucketback-domain/src/test/java/com/programmers/bucketback/domains/feed/implementation/FeedModifierTest.java
<br>
[OMCT-380]
피드 수정 테스트 기능 추가 73979544349250b0310b715dcb98a0d6ead2258e 
[OMCT-380]: https://ohmycourse.atlassian.net/browse/OMCT-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OMCT-380] 피드 수정 테스트 기능 추가

bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/domain/BucketInfo.java, bucketback-domain/src/test/java/com/programmers/bucketback/domains/bucket/domain/BucketInfoTest.java, bucketback-domain/src/test/java/com/programmers/bucketback/domains/feed/domain/FeedContentTest.java
<br>
410 
bucketInfo, feedConent 가 생성될 때의 상황에서 검증로직이 들어있어 해당 테스트를 진행함
null조건, magic number가 들어왔을 때 정상적으로 에러를 내뱉는지를 확인함
+ 테스트를 통해 bucketInfo의 검증 로직에 문제가 있었음을 확인하고 수정함
<br>
=> [OMCT-410]  domain validation test 및 refactoring

bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/response/FeedGetRankingResponse.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java, bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/dto/response/FeedGetRankingServiceResponse.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/config/RedisConfig.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/feed/FeedRedisManager.java, bucketback-infrastructure/src/main/java/com/programmers/bucketback/redis/feed/model/FeedRankingInfo.java
<br>
OMCT-271
- 피드에 좋아요나 상세 조회 될 경우 랭킹 상승
- 피드에 싫어요를 누를 경우 랭킹 하락
- 레디스를 이용하여 랭킹 기능을 구현하였습니다. 
- 최종적으로 feed id가 있는지 없는지 hash를 통해 확인하고 feed 관련 데이터를 추가 합니다. 517d04605dd02997af1a2cf0a44fc085021099b4 275105efc1aa7c3b9b5142e6a3afab9b58244b77
=> [OMCT-271] 피드 랭킹 기능 추가
