bucket-back/bucket-back-backend

- src/main/java/com/programmers/bucketback/domains/common/BaseEntity.java
- src/main/java/com/programmers/bucketback/domains/common/MemberUtils.java
- src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
- src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
- src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
- src/main/java/com/programmers/bucketback/domains/member/domain/MemberSecurity.java
- src/main/java/com/programmers/bucketback/domains/member/domain/MemberStatus.java
- src/main/java/com/programmers/bucketback/global/config/security/ApplicationConfiguration.java
- src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java
- src/main/java/com/programmers/bucketback/global/config/security/SecurityUtils.java
- src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtService.java
- src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-51
- JWT 토큰에 email 대신 memberId를 저장하도록 변경하였습니다.
- 회원 삭제 시 SecurityContext에서 memberId를 가져와서 회원을 조회합니다. 조회한 회원의 상태값을 DELTED로 변경합니다.
- BaseEntity의 createAt은 변경되지 않도록 @Column애 명시해주었습니다.  
<br>
탈퇴한 회원을 로그인을 할 수 없도록 로그인 실패 로직을 추가하였습니다.
> [OMCT-51] 회원 삭제 기능 구현

- src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
- src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
- src/main/java/com/programmers/bucketback/domains/item/application/MemberItemReader.java
- src/main/java/com/programmers/bucketback/domains/item/application/MemberItemRemover.java
- src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
<br>
OMCT-37
사용자가 담은 아이템 삭제 하는 기능 추가 하였습니다.
- 아이템 아이디와 일치하는 아이템을 사용자가 가지고 있다면 MEMBERS_ITEMS 테이블에서 삭제 합니다.
> [OMCT-37] 멤버 아이템 삭제 기능 추가

- src/main/java/com/programmers/bucketback/domains/common/vo/CursorPageParameters.java
- src/main/java/com/programmers/bucketback/domains/common/vo/CursorRequest.java
- src/main/java/com/programmers/bucketback/domains/vote/api/VoteController.java
- src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetByCursorResponse.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteAppender.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteCursorSummary.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteInfo.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteReader.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteRemover.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteSortCondition.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteStatusCondition.java
- src/main/java/com/programmers/bucketback/domains/vote/application/VoteSummary.java
- src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/GetVotesServiceResponse.java
- src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepository.java
- src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursor.java
- src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
- src/main/java/com/programmers/bucketback/global/error/exception/ErrorCode.java
<br>
OMCT-95
- 투표는 `진행 중인 투표`, `종료된 투표`, `내가 올린 투표`, `내가 참여한 투표` 4개의 목록을 조회할 수 있습니다.
- 위 4개의 목록은 기본적으로 최신순으로 정렬되며, 종료된 투표는 추가적으로 인기순으로 정렬될 수 있습니다.
- 인기순은 투표 참여자 수가 많은 순이며, 커서 ID는 참여자 수 + 투표 ID 두 개를 조합해서 생성하고 있습니다. 이 부분에 대해 문제가 있는데 아래 [고려해야 할 포인트]에서 설명하겠습니다.
이름 | 설명
-- | --
sortCondition | 정렬 기준(인기순, 최신순)
statusCondition | 투표 상태(진행중, 종료된,내가 올린, 내가 참여한)(필수)
hobby | 취미(필수)
cursorId | 커서ID
size | 페이지 사이즈
- 이전에 구현된 커서를 보면 Querydsl 내부에서 cursorId를 생성하여 비교하고, 구현 계층에서도 cursorId를 다시 계산해주는 것으로 압니다.
- 위의 부분을 개선하기 위해서 Querydsl에서 생성한 cursorId도 결괏값으로 함께 반환해주어 구현 계층에서는 cursorId를 계산할 필요가 없졌습니다.
- 현재 종료된 투표에서 **인기순** 조회는 투표 **참여자 수가 많은 순**으로 정렬이 됩니다. 따라서 커서 ID가 참여자 수와 투표 ID 를 통해 생성이 되는데 문제는 **참여자 수가 실시간으로 변하는 값**이라는 것 입니다. 참여자 수가 실시간으로 변하기 때문에 조회를 할 때 데이터가 누실될 경우가 있을 수 있습니다.
- …
> [OMCT-95] Vote 조건 검색 + 커서 페이지네이션 구현

- src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewCreateRequest.java
- src/main/java/com/programmers/bucketback/domains/review/api/dto/request/ReviewUpdateRequest.java
- src/main/java/com/programmers/bucketback/domains/review/application/ReviewStatistics.java
- src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepository.java
<br>
N/A
- jpql 집계함수에서 item id가 리뷰 테이블에 없는 경우 null을 반환한다.
- 이 때 반환 타입이 double 이라 초기화 하지 못해 예외가 발상하였다.
- double 대신 Double 타입으로 변경하고 null을 반환하도록 수정하였다. 
- 추후에 프론트와 의논하여 값을 내려주지 않을지 지금처럼 null을 반환할지 의논할 예정이다.
> NO-ZIRA: 아이템 상세조회 및 리뷰 평점 버그 수정

- src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepositoryForCursorImpl.java
- src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
- src/main/java/com/programmers/bucketback/domains/review/repository/ReviewRepositoryForCursorImpl.java
- src/main/java/com/programmers/bucketback/domains/vote/repository/VoteRepositoryForCursorImpl.java
<br>
NO-JIRA
- Nickname과 같은 VO를 추출하면서 기존의 Querydsl을 사용하면 조회가 안되는 문제가 발생했습니다.
- `member.nickname` -> `member.nickname.nickname` 과 같이 중간에 추출한 VO 클래스명을 추가하여 해결하였습니다.
<br>
> [NO-JIRA] VO 추출로 인한 커서 목록 조회 안되는 버그 해결

- bucketback-domain/src/main/java/com/programmers/bucketback/common/cursor/CursorUtils.java
<br>
NO-JIRA
- 빈 목록일 경우 lastSummary가 null 이기 때문에 cursorId가 없다는 예외가 발생했습니다.
- lastSummary 가 null이라면 cursorId도 null로 반환하도록 함으로써 버그를 해결했습니다.
- 추가로 CursorUtils 클래스를 유틸성 클래스로 만들기 위해서 final 클래스로 만들고 생성자를 private 하게 변경하였습니다.
<br>
> [NO-JIRA] 커서 조회 시 빈 목록일 경우 예외 발생하는 버그 해결 + CursorUtils 클래스 리팩토링

- bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/ReviewController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/review/api/dto/response/ReviewCreateResponse.java
<br>
리뷰생성할 때 아이템 아이디를 반환 하도록 기능 추가
OMCT-286
리뷰생성할 때 아이템 아이디를 반환 하도록 기능 추가
- 리뷰한 아이템의 아이디를 반환 합니다.
-
> [OMCT-286] 리뷰생성할 때 아이템 아이디를 반환 하도록 기능 추가

- bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/response/VoteGetResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/VoteService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/response/VoteGetServiceResponse.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteDetail.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteDetailInfo.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteInfo.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteSummary.java
<br>
NO-JIRA
- 종료된 투표와 진행 중인 투표 상태가 반대로 나오는 버그 수정 9530aa12d8eac6c4dbd5c9eba73a85e5d6d0b070
- 투표에서 선택한 아이템 id 안보이는 버그 수정 19372b0e9ebf09ae247b222794fa244fba14fd11
- 멀티모듈로 전환하는 과정에서 model 클래스들은 domain 모듈에 있기 때문에 `@JsonInclude(JsonInclude.Include.NON_NULL)`을 사용할 수 없게 되었습니다. 어노테이션 말고 yml에 아래 설정을 추가하여 이 문제를 해결할 수 있습니다.
```
jackson:
default-property-inclusion: non_null
```
<br>
> [NO-JIRA] 투표 상세 조회 관련 버그 수정

- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
- bucketback-domain/src/main/java/com/programmers/bucketback/common/model/Hobby.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursor.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursorImpl.java
<br>
나의 아이템 목록 조회에 취미 파라미터 추가
[OMCT-289]
나의 아이템 목록 조회에 취미 파라미터 추가
- 취미를 입력하면 나의 아이템 목록 조회중 입력한 취미와 일치하는 아이템을 반환 합니다.
[OMCT-289]: https://ohmycourse.atlassian.net/browse/OMCT-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OMCT-289] 나의 아이템 목록 조회에 취미 파라미터 추가

- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberRemover.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
<br>
NO-JIRA
- Member 엔티티에 프로필 이미지 전체 경로 저장 [7258a9b](https://github.com/bucket-back/bucket-back-backend/pull/145/commits/7258a9bc3e429692425796bebb051448953e4059)
- 프로필 이미지 수정 시 파일이 안올 경우 프로필 이미지 삭제 기능 추가 [aa5ee3a](https://github.com/bucket-back/bucket-back-backend/pull/145/commits/aa5ee3a7f24b1812c46dbddb909eee9f45c9186b)
- 피드 목록 조회 시 프로필 이미지도 같이 반환 [7ba81e9](https://github.com/bucket-back/bucket-back-backend/pull/145/commits/7ba81e97f4f197b7610cbbb430e791c74301dd21)
<br>
- 프로필 이미지도 추가 반환
> [NO-JIRA] 회원 프로필 이미지 관련 기능 추가 (프로필 이미지 삭제, 피드 목록 조회 시 프로필 이미지 반환)

- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/BucketController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/api/InventoryController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/inventory/application/InventoryService.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/inventory/implementation/InventoryReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/ItemReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursor.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/ItemRepositoryForCursorImpl.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursor.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepositoryForCursorImpl.java
<br>
288
1. 인벤토리와 버킷 경로 수정 33, 49 api (id값을 requestparam으로 받도록 변경, hobby를 requestparam으로 받도록 추가)
2. id값을 입력하는 경우는 수정하는 경우, 그렇지 않은 경우는 생성하는 경우로 생각한다.
3. 취미를 입력하는 경우는 취미별로 조회, 그렇지 않은 경우는 전체 조회를 할수 있도록 설정함
<br>
> [OMCT-288] bucket-inventory 생성 및 수정시 조회하는  api 통일

- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Voter.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteManager.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoterReader.java
- bucketback-domain/src/test/java/com/programmers/bucketback/domains/vote/implementation/VoteManagerTest.java
- bucketback-domain/src/testFixtures/java/com/programmers/bucketback/domains/vote/domain/VoterBuilder.java
<br>
OMCT-324
- `deleteByVoteAndMemberId` 메서드가 실행될 때 주어진 vote의 voters 리스트에서 해당 voter를 삭제하도록 하고, voters 리스트에서 없다는 것을 통해 테스트를 검증하였습니다.
- 처음 투표를 참여할 때는 생성된 voter의 정보가 주어진 투표 정보들과 같은지 비교하였습니다.
- 투표 재참여 테스트는 기존의 투표자의 ItemId가 새로 선택한 ItemId와 같은지, 나머지 투표 정보들은 그대로인지 비교하여 검증하였습니다.
<br>
> [OMCT-324] VoteManager 단위 테스트 추가

- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/request/MemberItemDeleteRequest.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
- bucketback-domain/src/main/java/com/programmers/bucketback/common/model/ItemRemovalList.java
<br>
아이템 아이디 목록을 받아서 삭제할 수 있도록 기능 추가
[OMCT-331]
아이템 아이디 목록을 받아서 삭제할 수 있도록 기능 추가
- 내부적으로는 단일 삭제 메서드를 for문으로 호출하고 있습니다. 이 부분은 추후 기능개선을 할 때 쿼리 한번에 삭제될 수 있도록 수정할 예정 입니다!
<br>
[OMCT-331]: https://ohmycourse.atlassian.net/browse/OMCT-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [OMCT-331] 아이템 아이디 목록을 받아서 삭제할 수 있도록 기능 추가

- bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/api/FeedController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/feed/application/FeedService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/implementation/FeedCursorReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursor.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/feed/repository/FeedRepositoryForCursorImpl.java
<br>
[NO-JIRA]
- 요구사항 혼동으로 인한 잘못된 변수명 수정 a4e27d8fad47304411ee5413f2506e39530ad54a
- nickname이 좋아요 누른 피드만 볼 수 있도록 onlyNicknameLikeFeeds이 true일 경우 nickname이 올린 피드만 볼 수 있게 하는 기능을 넘기도록 수정 23dc3dcd602ad27dcf6d03c6f02fe26267573d4b
> [NO-JIRA] 아이템 목록 조회 좋아요 누른 피드 보기 버그 수정

- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/domain/Member.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/implementation/MemberModifier.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberInfo.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/member/model/MemberProfile.java
<br>
NO-JIRA
**기존 방식**
- 프로필 이미지를 S3 버킷 주소를 그대로 저장
- 프로필 이미지 이름은 회원 id로 생성
**변경된 방식**
- 프로필 이미지를 이름 그대로 저장하고, 주소를 얻는 게더 메서드 따로 생성
- 프로필 이미지 이름은 UUID로 생성
<br>
> [NO-JIRA] 회원 프로필 이미지 주소 대신 이미지 이름으로 저장하도록 변경

- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetByCursorResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/api/dto/response/BucketGetMemberItemResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/BucketService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/dto/response/BucketGetCursorServiceResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/bucket/application/dto/response/BucketGetMemberItemServiceResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/api/dto/response/CommentGetCursorResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/CommentService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/dto/response/CommentGetCursorServiceResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/comment/application/dto/response/CommentsGetServiceResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/ItemController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/api/dto/response/MemberItemGetByCursorResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/ItemService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/item/application/dto/MemberItemGetServiceResponse.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/implementation/BucketReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/bucket/repository/BucketRepository.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/implementation/CommentReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/comment/repository/CommentRepository.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/implementation/MemberItemReader.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/item/repository/MemberItemRepository.java
<br>
no-jira
각 커서 조회 api에 총 개수를 count할 수 있는 반환값을 추가함
1. 피드 댓글 목록 조회
2. 버킷 목록 조회
3. 버킷 목록 조회와 수정을 위한 내가 담은 아이템 목록 조회
4. 내가 담은 아이템을 취미별로 조회
<br>
> [NO-JIRA] 커서 목록조회 : 총 개수를 read 해오는 반환값 추가

- bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/api/dto/request/VoteCreateRequest.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/vote/application/dto/request/VoteCreateServiceRequest.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/domain/Vote.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteAppender.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/implementation/VoteManager.java
- bucketback-domain/src/main/java/com/programmers/bucketback/domains/vote/model/VoteCreateImplRequest.java
<br>
OMCT-409
**기존 투표**
```
- 투표는 생성된 일시부터 24시간동안 열린다.
- 투표자 수에 제한이 없다.
```
**추가된 요구사항**
```
- 투표를 생성할 때 최대 투표자 수를 정할 수 있다. (option)
- 지정한 투표자 수가 되면 투표는 그 즉시 종료된다.
````
**보충해야 할 부분**
- 투표 랭킹에서 24시간 이내 종료된 투표 삭제하기
- 투표 첫 참여와 재참여 API 분리하기
💡 일단 프론트와 합의한 요구사항 먼저 추가하고 이때 발생한 동시성 문제는 추후에 해결하기로 했습니다.
<br>
> [OMCT-409] 최대 투표자 수를 제한하는 요구사항 추가

- bucketback-api/build.gradle
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/MemberController.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/dto/response/AccessTokenResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/api/dto/response/MemberLoginResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberSecurityManager.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/MemberService.java
- bucketback-api/src/main/java/com/programmers/bucketback/domains/member/application/dto/response/MemberLoginServiceResponse.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/cache/CacheConfiguration.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/cache/CacheType.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/SecurityManager.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtAuthenticationFilter.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtConfig.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/jwt/JwtService.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/error/GlobalExceptionHandler.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/util/MemberUtils.java
- bucketback-common/src/main/java/com/programmers/bucketback/error/ErrorCode.java
<br>
OMCT-411
1. 회원이 로그인 정보를 입력하고 로그인을 시도한다.
2. 서버에서는 회원이 입력한 정보와 DB에 저장된 회원 정보를 비교하여 일치하면 로그인 처리를 한다.
3. 로그인 응답값으로는 요청 바디에 회원ID, 닉네임, Access Token이 담겨있고, 쿠키에는 Refresh Token이 담겨있다.
- Access Token과 함께 Refresh Token도 함께 만들어서 요청값에 추가
1. 회원이 로그아웃 또는 회원 탈퇴를 시도한다. (로그아웃 API 새로 추가함)
2. 서버에서는 저장해둔 Refresh Token을 삭제한다.
1. 프론트에서 서버로 Access Token은 헤더에, Refresh Token은 쿠키로 보낸다.
2. Refresh Token이 유효하고 Access Token이 유효하지 않다면 새로운 Access Token을 생성해서 반환한다.
3. Refresh Token이 유효하고 Access Token도 유효하면 들어온 Access Token을 요청 바디에 실어 그대로 반환한다.
4. 2번과 3번이 아닌 경우에는 예외를 터뜨린다.
- 로그인 할 때 캐싱
- 로그아웃 & 회원 탈퇴 시 제거
<br>
> [OMCT-411] 로그인 연장 기능 추가 - Refresh token으로 Access token 재발급

- bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SseEmitters.java
- bucketback-api/src/test/java/com/programmers/bucketback/domains/sse/SseEmittersTest.java
<br>
408
댓글을 달면 알림을 수신받는 유저가 로그인되어있지 않은 경우 알림을 보내면 NPE 발생(500에러 응답)
그럼에도 불구하고 댓글을 달면 저장은 되고있어 비즈니스에는 영향을 주지 않기 때문에 200성공메세지로 전달하도록 수정함
차후 보완 포인트 : 이런 이벤트에 대한 알림을 지연시켜두었다가 다시 발송하는 이벤트 기반 처리 로직이 있으면 좋을 것 같음
https://techblog.woowahan.com/7835/
<br>
> [OMCT-408] 알림 전송 로직 수정

- bucketback-api/src/main/java/com/programmers/bucketback/domains/sse/SseEmitters.java
- bucketback-api/src/main/java/com/programmers/bucketback/global/config/security/SecurityConfiguration.java
<br>
408
- sseEmitter의 생명주기가 길면, 그만큼의 http 커넥션과 db 커넥션을 물고 있게됨(osivTrue상황)
- 그래서 이 생명주기를 짧게 유지하고, 재요청을 보내는 방식으로 emitter의 생명주기를 짧게 만듦
- but security 관련 문제가 발생함
**이유**
emitter가 timeOut의 콜백으로 스레드를 반환하면, 시큐리티의 생명 주기도 영향을 받는다.
시큐리티도 스레드와 생명주기가 같아서, 스레드를 반환하고 재할당을 받으면 그떄 securityContext는 존재하지 않아 accessDenied 예외를 맞게 된다.
emitter내의 예외는 아니기 때문에 emitter에서 콜백으로 감지하는 error도 발생하지 않고 나머지 기능들도 정상 작동하는걸 보면, 시큐리티 관련한 문제로 폭을 좁혀볼 수 있었다.
정리 : subscribe의 커넥션이 emitter의 생명 주기가 되면 종료된다. 그리고 바로 재요청을 보내서 새로운 스레드를 할당받는데, 이떄는 securitycontext를 새로 가질 수 없어 accessDenied가 발생한다.
해결 : subscribe api를 사요할 떄 securityconfiguration에 필터를 거치지 않도록 수정하여 예외없이 정상적인 종료를 하도록 수정함.
<br>
> [OMCT-408] emitter 생명주기를 짧게 수정함, securityConfiguration에 subscribe 예외 처리
